# Generated by Django 5.2.5 on 2025-08-12 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, verbose_name='Nome do campo')),
                ('field_type', models.CharField(choices=[('CQB', 'CQB (Close Quarters Battle)'), ('MATA', 'Mata'), ('MISTO', 'Misto')], max_length=10, verbose_name='Tipo de Campo')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('social_media', models.JSONField(blank=True, default=dict, null=True, verbose_name='Redes sociais')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('operating_hours', models.TextField(verbose_name='Horário de funcionamento')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Organizador')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='FieldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.URLField(verbose_name='URL da foto')),
                ('order_in_gallery', models.PositiveIntegerField(default=0, verbose_name='Ordem na galeria')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='fields.field', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'Foto do campo',
                'verbose_name_plural': 'Fotos dos campos',
                'ordering': ['order_in_gallery'],
            },
        ),
    ]
