# Generated by Django 5.2.5 on 2025-10-31 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, verbose_name='Nome do campo')),
                ('field_type', models.CharField(choices=[('CQB', 'CQB'), ('MATA', 'Mata'), ('MISTO', 'Misto'), ('SPEED', 'Speed')], max_length=10, verbose_name='Tipo de Campo')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('state', models.CharField(max_length=100, verbose_name='Estado')),
                ('state_abbreviation', models.CharField(max_length=2, unique=True, verbose_name='Abreviação do Estado')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('phone', models.CharField(validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)], verbose_name='Telefone')),
                ('description', models.TextField(validators=[django.core.validators.MinLengthValidator(60)], verbose_name='Descrição')),
                ('operating_hours', models.TextField(verbose_name='Horário de funcionamento')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
            ],
            options={
                'verbose_name': 'Campo',
                'verbose_name_plural': 'Campos',
            },
        ),
        migrations.CreateModel(
            name='FieldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='field_photos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Foto do campo',
                'verbose_name_plural': 'Fotos dos campos',
            },
        ),
    ]
