# Generated by Django 5.2.5 on 2025-10-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='state_abbreviation',
            field=models.CharField(max_length=2, verbose_name='Abreviação do Estado'),
        ),
    ]
