# Generated by Django 5.2.5 on 2025-11-07 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_alter_field_state_abbreviation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('field_name', ''), _negated=True), name='field_field_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('address', ''), _negated=True), name='field_address_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('state', ''), _negated=True), name='field_state_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('state_abbreviation', ''), _negated=True), name='field_state_abbrev_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('city', ''), _negated=True), name='field_city_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('phone', ''), _negated=True), name='field_phone_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('description', ''), _negated=True), name='field_description_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='field',
            constraint=models.CheckConstraint(condition=models.Q(('operating_hours', ''), _negated=True), name='field_operating_hours_not_empty'),
        ),
    ]
