# Generated by Django 5.2.5 on 2025-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0004_field_field_field_name_not_empty_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='fieldphoto',
            constraint=models.CheckConstraint(condition=models.Q(('photo', ''), _negated=True), name='fieldphoto_photo_not_empty'),
        ),
    ]
