# Generated by Django 5.2.5 on 2025-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
