# Generated by Django 5.2.5 on 2025-11-07 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='phone',
            field=models.CharField(default='(99) 99999-9999', validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)], verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
