# Generated by Django 5.2.5 on 2025-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_remove_organizer_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
