# Generated by Django 5.2.5 on 2025-11-07 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_organizer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='field_photos/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='phone',
            field=models.CharField(null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)], verbose_name='Telefone'),
        ),
    ]
