# Generated by Django 5.2.5 on 2025-11-07 14:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_organizer_profile_photo_alter_organizer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='phone',
            field=models.CharField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(15), django.core.validators.MaxLengthValidator(15)], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='field_photos/', verbose_name='Foto'),
        ),
    ]
