# Generated by Django 5.2.5 on 2025-10-16 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_alter_organizer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
