# Generated by Django 5.2.5 on 2025-11-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_alter_organizer_phone_alter_organizer_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/', verbose_name='Foto'),
        ),
    ]
