# Generated by Django 5.2.5 on 2025-11-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizers', '0005_alter_organizer_profile_photo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizer',
            constraint=models.CheckConstraint(condition=models.Q(('username', ''), _negated=True), name='organizer_username_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='organizer',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='organizer_email_not_empty'),
        ),
    ]
